#####################
##     Example     ##
#####################

#  [TMDb number]: # [Name of movie]
#    title: [Name of movie]
#    alt_title: [it's sometimes also called]
#    sort_title: [how to sort movie]
#    url_poster: https://theposterdb.com/api/assets/[poster-number]

#################################################
##     Plex Auto-naming and Metadata Fixes     ##
#################################################

metadata:

  7211: # Dan In Real Life
    url_poster: https://theposterdb.com/api/assets/113756

  2666: # Dark City
    url_poster: https://image.tmdb.org/t/p/original/4WRQwCnM70ddDaYmH4QBz01kB11.jpg

  1410: # Dark Star
    content_rating: 12
    url_poster: https://image.tmdb.org/t/p/original/nybQ7cBbSlgCikFhpULiKCfJcuQ.jpg

  387: # Das Boot
    sort_title: Das Boot
    url_poster: https://theposterdb.com/api/assets/164559

  35595: # Dave Chappelle: HBO Comedy Half Hour
    sort_title: Dave Chappelle 1

  16275: # Dave Chappelle: Killin' Them Softly
    sort_title: Dave Chappelle 2

  20147: # Dave Chappelle: For What It's Worth
    sort_title: Dave Chappelle 3

  444705: # Dave Chappelle: The Age of Spin
    sort_title: Dave Chappelle 4

  444706: # Dave Chappelle: Deep in the Heart of Texas
    sort_title: Dave Chappelle 5

  488223: # Dave Chappelle: Equanimity
    sort_title: Dave Chappelle 6

  494368: # Dave Chappelle: The Bird Revelation
    sort_title: Dave Chappelle 7

  624932: # Dave Chappelle: Sticks & Stones
    sort_title: Dave Chappelle 8

  879540: # Dave Chappelle: The Closer
    sort_title: Dave Chappelle 9
    url_poster: https://theposterdb.com/api/assets/279560

  32182: # David Cross: The Pride Is Back
    sort_title: David Cross 1

  41994: # David Cross: Bigger and Blackerer
    sort_title: David Cross 3

  408546: # David Cross: Making America Great Again
    sort_title: David Cross 4

  601938: # David Cross: Oh, Come On
    sort_title: David Cross 5

  923: # Dawn of the Dead (1978)
    url_poster: https://image.tmdb.org/t/p/original/s72VCWVWZv2Pc8M60KnuqJsBN58.jpg

  924: # Dawn of the Dead (2004)
    url_poster: https://www.themoviedb.org/t/p/original/ttquyxStEEctzghtA2f4PUGprDr.jpg

  8408: # Day of the Dead (1985)
    url_poster: https://image.tmdb.org/t/p/original/xZMACQjw1CCZormdoB2Ea4P7krs.jpg

  10651: # The Dead Pool
    url_poster: https://theposterdb.com/api/assets/857

  293660: # Deadpool
    url_poster: https://theposterdb.com/api/assets/135779
    sort_title: Deadpool 1

  383498: # Deadpool 2
    url_poster: https://theposterdb.com/api/assets/135780
    sort_title: Deadpool 2

  533535: # Deadpool & Wolverine
    url_poster: https://theposterdb.com/api/assets/513321
    sort_title: Deadpool 3

  505026: # Death on the Nile
    url_poster: https://theposterdb.com/api/assets/223827

  36724: # The Decline of Western Civilization II
    url_poster: https://www.themoviedb.org/t/p/original/z0tv8cM9666wJIqen4eAkr23Hr9.jpg

  11778: # The Deer Hunter
    url_poster: https://image.tmdb.org/t/p/original/9IoJFxE18kD3zDx6v2MBGOYYrFH.jpg

  892: # Delicatessen
    url_poster: https://theposterdb.com/api/assets/167028

  9739: # Demolition Man
    url_poster: https://theposterdb.com/api/assets/67020

  20352: # Despicable Me
    url_poster: https://theposterdb.com/api/assets/138808

  93456: # Despicable Me 2
    url_poster: https://theposterdb.com/api/assets/138809

  324852: # Despicable Me 3
    url_poster: https://theposterdb.com/api/assets/138810

  519182: # Despicable Me 4
    url_poster: https://theposterdb.com/api/assets/528343

  1433: # The Devil's Backbone
    url_poster: https://image.tmdb.org/t/p/original/iP1z1aJzPnkP8FHg77TS7ukqoEZ.jpg

  681: # Diamonds Are Forever
    url_poster: https://theposterdb.com/api/assets/115669

  36669: # Die Another Day
    url_poster: https://theposterdb.com/api/assets/115683

  562: # Die Hard
    sort_title: Die Hard 1
    url_poster: https://theposterdb.com/api/assets/558

  1573: # Die Hard 2
    sort_title: Die Hard 2
    url_poster: https://theposterdb.com/api/assets/559

  1572: # Die Hard with a Vengeance
    sort_title: Die Hard 3
    url_poster: https://theposterdb.com/api/assets/560

  984: # Dirty Harry
    url_poster: https://theposterdb.com/api/assets/852

  14577: # Dirty Work
    url_poster: https://image.tmdb.org/t/p/original/btYKWL9SP12nhkcw8EkMG3aFtga.jpg

  376134: # The Discovery
    url_poster: https://image.tmdb.org/t/p/original/nLIDouFvreSrs8xK62zuvpEPDw0.jpg

  5257: # The Dish
    url_poster: https://image.tmdb.org/t/p/original/4hyYzQkpvC4wfQsZ2fijzZ56FsO.jpg

  10411: # The Distinguished Gentleman
    url_poster: https://image.tmdb.org/t/p/original/ny722xPMhsY6JlRmQQjLZs7JP0S.jpg

  284052: # Doctor Strange
    url_poster: https://theposterdb.com/api/assets/9788

  453395: # Doctor Strange in the Multiverse of Madness
    url_poster: https://theposterdb.com/api/assets/234599

  1832: # Dogma
    url_poster: https://theposterdb.com/api/assets/331272

  470942: # Don't Break Down: A Film About Jawbreaker
    content_rating: 15

  9101: # Down Periscope
    url_poster: https://image.tmdb.org/t/p/original//brleKcHsirTw7lFqcgUMOfgL2nl.jpg

  646: # Dr. No
    url_poster: https://theposterdb.com/api/assets/115663

  935: # Dr. Strangelove
    url_poster: https://theposterdb.com/api/assets/214759

  10023: # Dragnet
    url_poster: https://image.tmdb.org/t/p/original/77H17YDeHoJCHebpfGF1rY3Dfof.jpg

  24099: # Dreamscape
    url_poster: https://theposterdb.com/api/assets/33713

  8467: # Dumb and Dumber
    url_poster: https://image.tmdb.org/t/p/original/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg

  10719: # Elf
    url_poster: https://image.tmdb.org/t/p/original/oOleziEempUPu96jkGs0Pj6tKxj.jpg

  614934: # Elvis
    url_poster: https://image.tmdb.org/t/p/original/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg

  862965: # Emily the Criminal
    url_poster: https://image.tmdb.org/t/p/original/hFuynYYxZIiWR4cRlwzmteH2diL.jpg

  4523: # Enchanted
    url_poster: https://theposterdb.com/api/assets/6258

  853: # Enemy at the Gates
    url_poster: https://image.tmdb.org/t/p/original/m8B0mWL7NuFe6b9rdZBVmHFnEQK.jpg

  10649: # The Enforcer
    url_poster: https://theposterdb.com/api/assets/855

  476549: # Escape From Mr. Lemoncello's Library
    content_rating: 8

  601: # E.T. the Extra-Terrestrial
    url_poster: https://image.tmdb.org/t/p/original/pEKStszBzTZCvR0H4tosjqxmE7X.jpg

  524434: # Eternals
    url_poster: https://theposterdb.com/api/assets/153775

  554603: # The Eugenics Crusade
    content_rating: 13

  8413: # Event Horizon
    url_poster: https://image.tmdb.org/t/p/original/cHoeg3gAD5w63Et5DImY1Jb7HaO.jpg

  2320: # Executive Decision
    url_poster: https://image.tmdb.org/t/p/original/ad2bXNH8M3BI0YYWQ8f31qWiuk0.jpg

  754: # Face/Off
    url_poster: https://image.tmdb.org/t/p/original/69Xzn8UdPbVnmqSChKz2RTpoNfB.jpg

  9276: # The Faculty
    url_poster: https://theposterdb.com/api/assets/33949

  746036: # The Fall Guy
    url_poster: https://image.tmdb.org/t/p/original/wfBuFUFnYr6o05S98EkAkYou7S7.jpg

  5994: # The Family Man
    url_poster: https://www.themoviedb.org/t/p/original/hvPltBKYxVYLPGvUJ9t8Pu8sXeT.jpg

  101519: # A Fantastic Fear of Everything
    url_poster: https://image.tmdb.org/t/p/original/sMZyKSo8b47VW1h2zjjGUZIefV1.jpg

  436305: # The Farthest
    url_poster: https://theposterdb.com/api/assets/21494

  18: # The Fifth Element
    url_poster: https://theposterdb.com/api/assets/14377

  8738: # The Final Countdown
    url_poster: https://theposterdb.com/api/assets/179552

  127380: # Finding Dory
    sort_title: Finding 2

  12: # Finding Nemo
    sort_title: Finding 1

  1368: # First Blood
    url_poster: https://www.themoviedb.org/t/p/original/a9sa6ERZCpplbPEO7OMWE763CLD.jpg

  236399: # Flowers in the Attic
    content_rating: 13

  938: # For a Few Dollars More
    url_poster: https://www.themoviedb.org/t/p/original/ooqASvA7qxlTVKL3KwOzBwy57Dh.jpg

  14799: # For Your Consideration
    url_poster: https://www.themoviedb.org/t/p/original/fvXClgY4ZJ7dBxalFuxPgb4nJ9s.jpg

  699: # For Your Eyes Only
    url_poster: https://theposterdb.com/api/assets/115674

  830: # Forbidden Planet
    url_poster: https://image.tmdb.org/t/p/original/faWaEdEC6EbBL7M0PbUISbxTM1j.jpg

  9870: # Forgetting Sarah Marshall
    url_poster: https://image.tmdb.org/t/p/original/d4elOzyhNWVlxpG7BwigrumkFTe.jpg

  37495: # Four Lions
    url_poster: https://image.tmdb.org/t/p/original/x4JzaRPXBs9wiHCe3e3ymXWuwfd.jpg

  983406: # Fourth of July
    content_rating: 17

  12149: # Frailty
    url_poster: https://image.tmdb.org/t/p/original/yBXrSxXoGkyexS3ysUOxEpE2P94.jpg

  539892: # Freaks
    url_poster: https://theposterdb.com/api/assets/163349

  551804: # Freaky
    url_poster: https://image.tmdb.org/t/p/original/3MhBQLHBWUigh9ZJ2xV5KeHn8hq.jpg

  542178: # The French Dispatch
    url_poster: https://image.tmdb.org/t/p/original/6JXR3KJH5roiBCjWFt09xfgxHZc.jpg

  10559: # Frequency
    url_poster: https://theposterdb.com/api/assets/108800

  58151: # Fright Night (2011)
    url_poster: https://image.tmdb.org/t/p/original/xOCYCTU3MKuPpxIUcGzG52ZEBbm.jpg

  657: # From Russia With Love
    url_poster: https://theposterdb.com/api/assets/115664

  786892: # Furiosa - A Mad Max Saga
    url_poster: https://image.tmdb.org/t/p/original/1pyWL29UkXYF2rlM2PZ339PM2QN.jpg