#####################
##     Example     ##
#####################

#  [TVDb number]: # [Name of show]
#    title: [Name of show]
#    alt_title: [it's sometimes also called...]
#    sort_title: [how to sort show]
#    url_poster: https://theposterdb.com/api/assets/[poster-number]

#################################################
##     Plex Auto-naming and Metadata Fixes     ##
#################################################

metadata:

  72173: # Arrested Development
    url_poster: https://artworks.thetvdb.com/banners/posters/5c6c6bd1ea050.jpg
    seasons:
      1:
        url_poster: https://artworks.thetvdb.com/banners/seasons/72173-1.jpg
        episodes:
          1:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75834.jpg
          2:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75835.jpg
          3:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75836.jpg
          4:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75837.jpg
          5:
            title: "Visiting Hours"
            summary: "Michael sets up an 'intimate conjugal visit' for his parents, while it is revealed that George Sr. had an affair with Kitty, his secretary who recently slept with Gob. Tobias and Lindsay see a marriage counselor."
            originally_available: 2003-12-07
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75839.jpg
          6:
            title: "Charity Drive"
            summary: "Michael and Lindsay try to prove their charitable sides to each other. Gob demands George Michael's respect, and Buster continues avoiding Lucille 2."
            originally_available: 2003-11-30
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75838.jpg
          7:
            title: "My Mother, The Car"
            summary: "Michael loses his short-term memory, which Lucille uses to her advantage. Gob attempts to use the family yacht before Michael sells it. George Michael and Maeby attempt to see an R-rated movie about cousins having an affair. Buster and Lucille 2 take 'the next step'."
            originally_available: 2003-12-21
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75841.jpg
          8:
            title: "In God We Trust"
            summary: "Michael attempts to fire the family's incompetent, but likeable attorney. George Michael impresses Maeby with a muscle suit for the Living Classics pagent. Tobias has a psychological affliction where he is unable to take off his clothes."
            originally_available: 2003-12-14
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75840.jpg
          9:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75842.jpg
          10:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75843.jpg
          11:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75844.jpg
          12:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75845.jpg
          13:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75846.jpg
          14:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75847.jpg
          15:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75848.jpg
          16:
            title: "Missing Kitty"
            summary: "Gob attempts to make good on his promise to make the family yacht disappear. Meanwhile, Lindsay and Maeby try to track down Lindsay's grandmother, Tobias seeks George Sr.'s respect, and Michael attempts to fire Kitty, who claims to have information that could bring down the company."
            originally_available: 2004-03-28
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75850.jpg
          17:
            title: "Altar Egos"
            summary: "Michael attempts to have a one-night stand with an attorney whom he doesn't know is not only blind, but the prosecutor who is trying to put his father in jail. Also, Gob gets married on a dare, Maeby pretends to be a girl with a made up disease, and George Sr.'s admirer turns out to be an undercover SEC agent who has truly fallen for him."
            originally_available: 2004-03-17 
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75851.jpg
          18:
            title: "Justice Is Blind"
            summary: "Gob steals a file on the government's case against the Bluth Company that Maggie had given to Michael. Tobias is sent to Maggie's house to get evidence, George Michael tries to prove Maeby's fraud, and Lindsay fights to remove the Ten Commandments from the courthouse lawn."
            originally_available: 2004-03-21            
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75849.jpg
          19:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75852.jpg
          20:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75853.jpg
          21:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75854.jpg
          22:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75855.jpg
      2:
        url_poster: https://artworks.thetvdb.com/banners/seasons/72173-2.jpg
        episodes:
          1:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75856.jpg
          2:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75857.jpg
          3:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75858.jpg
          4:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75859.jpg
          5:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75860.jpg
          6:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75861.jpg
          7:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75862.jpg
          8:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75863.jpg
          9:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75864.jpg
          10:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75865.jpg
          11:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75866.jpg
          12:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75867.jpg
          13:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75868.jpg
          14:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75869.jpg
          15:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75870.jpg
          16:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75871.jpg
          17:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75872.jpg
          18:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/75873.jpg
      3:
        url_poster: https://artworks.thetvdb.com/banners/seasons/72173-3.jpg
        episodes:
          1:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/302635.jpg
          2:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306154.jpg
          3:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306155.jpg
          4:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306156.jpg
          5:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306157.jpg
          6:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306158.jpg
          7:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306159.jpg
          8:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/302606.jpg
          9:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/304984.jpg
          10:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306160.jpg
          11:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306161.jpg
          12:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306162.jpg
          13:
            url_poster: https://artworks.thetvdb.com/banners/episodes/72173/306163.jpg
      4:
        url_poster: https://artworks.thetvdb.com/banners/seasons/72173-4-5.jpg
      5:
        url_poster: https://artworks.thetvdb.com/banners/v4/season/1877437/posters/6093fb3da77e7.jpg